services:
  - type: web
    name: fraud-detection-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python fraud_detection.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

